### ISSUE TITLE
A composable that requires access to the Nuxt instance was called outside of a plugin

### ISSUE THREAD

**Issue by IlyaSemenov** [enkot/nuxt-open-fetch#12]
### Problem

I need to make two calls to OpenAPI in a nuxt plugin, and it's impossible to do with `nuxt-open-fetch`, as the second call crashes with: _A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables`_.

### Reason

In Nuxt, there is a clear separation: `useFetch` is a composable, and `$fetch` is a function which is not coupled to Nuxt component render loop (it's essentially a renamed ofetch).

In nuxt-open-fetch, `$clientFetch` repeats `$fetch` contract but in fact it internally depends on Nuxt instance.

There problem is here:
https://github.com/enkot/nuxt-open-fetch/blob/d67634a23f6ae95fb55623cbb0319901fccb81ff/src/runtime/clients.ts#L118-L120
and here, which calls `useNuxtApp`:
https://github.com/enkot/nuxt-open-fetch/blob/d67634a23f6ae95fb55623cbb0319901fccb81ff/src/runtime/clients.ts#L101-L104

I suppose instead of doing `const { $openFetch } = useNuxtApp()` it should be looking up `useRuntimeConfig().public.openFetch.clients[arg]` directly; moreover, I believe it should be doing that once in `createOpenFetchClient` (not once per `$clientFetch` invocation).

**Comment by enkot** [comment]
@IlyaSemenov Could you please provide an example of your plugin?

**Comment by enkot** [comment]
Had a discussion here https://discord.com/channels/473401852243869706/897487139888062506/1162448006088511518 regarding this problem and currently working on another approach for `$[client]Fetch`.

**Comment by IlyaSemenov** [comment]
Good point, I over-generalized the problem. In a plugin itself, double `$clientFetch` works fine.

The problem appears in a plugin like this:

```ts
export default defineNuxtPlugin(async () => {
  const auth = useAuth()
  await auth.init()
  return {
    provide: { auth },
  }
})
```

where useAuth is a pinia/nuxt store:

```ts
import { defineStore } from "pinia"

export const useAuth = defineStore(
  "auth",
  () => {
    async function init() {
      await $clientFetch("/user/profile/").catch(() => {})
      await $clientFetch("/user/profile/").catch(() => {})
    }

    return {
      init,
    }
  },
)
```

I'll try to come up with a Stackblitz repro if needed.

**Comment by enkot** [comment]
@IlyaSemenov Starting from 3.0 we should get clients from the `useNuxtApp()`, so we never access the Nuxt instance inside `$clientFetch`.
```ts
import { defineStore } from "pinia"

export const useAuth = defineStore(
  "auth",
  () => {
    const { $clientFetch } = useNuxtApp()

    async function init() {
      await $clientFetch("/user/profile/").catch(() => {})
      await $clientFetch("/user/profile/").catch(() => {})
    }

    return {
      init,
    }
  },
)
```
