### ISSUE TITLE
indirect export not found: OpenFetchClient

### ISSUE THREAD

**Issue by GreyXor** [enkot/nuxt-open-fetch#25]
Hello,
I've added the module to my nuxt.config.ts as well as to my devDependencies. I launch my project with `nuxt dev`. And this error appears in the browser console.

`Uncaught SyntaxError: indirect export not found: OpenFetchClient [imports.mjs:27:56](virtual:nuxt:REDACTED/nuxt/imports.mjs)`

`export { createOpenFetch, openFetchRequestInterceptor, OpenFetchClient, OpenFetchOptions } from 'REDACTED/node_modules/.pnpm/nuxt-open-fetch@0.5.0_rollup@4.12.0/node_modules/nuxt-open-fetch/dist/runtime/fetch';`

If I add an openapi spec and the configuration as indicated in the documentation, I get the same error message
Did I miss something ? 
Thanks

**Comment by enkot** [comment]
Hi @GreyXor 
Can't reproduce, could you please make a repro here? https://stackblitz.com/edit/github-sr3krw?file=app.vue 

Note: type highlighting does not work on Stackblitz

**Comment by GreyXor** [comment]
Sorry that's actually not seems to be related to nuxt-open-fetch.
