### ISSUE TITLE
Method error type (Vue: Type string is not assignable to type never)

### ISSUE THREAD

**Issue by dwins-dev** [enkot/nuxt-open-fetch#26]
Hi
I have a problem with typing
<img width="730" alt="image" src="https://github.com/enkot/nuxt-open-fetch/assets/82148482/aaa538af-fbaf-4a38-8aa3-81cf075754af">
Moreover, the interface contains these methods
<img width="636" alt="image" src="https://github.com/enkot/nuxt-open-fetch/assets/82148482/b02e177f-ed00-4347-9858-093c80dc8dc4">
<img width="806" alt="image" src="https://github.com/enkot/nuxt-open-fetch/assets/82148482/050010f9-04bf-4b4f-ad70-c1ac90f21a71">
schema: "https://petstore3.swagger.io/api/v3/openapi.json"
Please help me

**Comment by hempflower** [comment]
Same issue.
But I seem to have found the cause of this problem.
(I'm sorry for my poor English.)
### Resaon
In this file https://github.com/enkot/nuxt-open-fetch/blob/main/src/runtime/fetch.ts#L17
```typesceipt
export type ParamsOption<T> = T extends { parameters?: any, query?: any } ? T["parameters"] : never
```
If api not have ‘parameters’ or ‘query’, Then ParamsOption<T> = 'never'.

Type `UseOpenFetchOptions`  definition is as follows

```
type UseOpenFetchOptions<
  Method,
  LowercasedMethod,
  Params,
  ResT,
  DataT = ResT,
  PickKeys extends KeysOf<DataT> = KeysOf<DataT>,
  DefaultT = null,
  Operation = 'get' extends LowercasedMethod ? ('get' extends keyof Params ? Params['get'] : never) : LowercasedMethod extends keyof Params ? Params[LowercasedMethod] : never
> =
  ComputedMethodOption<Method, Params>
  & ComputedOptions<ParamsOption<Operation>>
  & ComputedOptions<RequestBodyOption<Operation>>
  & Omit<UseFetchOptions<ResT, DataT, PickKeys, DefaultT>, 'query' | 'body' | 'method'>
```
ParamsOption<Operation> =never, 
then ComputedOptions<ParamsOption<Operation>> = never.
So UseOpenFetchOptions = never.

When I  changed  `UseOpenFetchOptions`  definition, it's working.
 ```typesceipt
export type ParamsOption<T> = T extends { parameters?: any, query?: any } ? T["parameters"] : {}
```
