### ISSUE TITLE
Indirect export not found

### ISSUE THREAD

**Issue by danierukun** [enkot/nuxt-open-fetch#28]
Hi, I've followed the setup guide, but everytime I try to use a use<client>() the page returns a 500 with the message `indirect export not found: Component`.

I've reproduced this on a fresh project, installing only nuxt-open-fetch. I'm also using remote schemas. Any help is appreciated.

**Comment by enkot** [comment]
Could you please make a reproduction?
For me it works fine https://stackblitz.com/edit/nuxt-starter-zdn6t6?file=nuxt.config.ts,app.vue

**Comment by danierukun** [comment]
I'm unable to fully reproduce in a web environment, however I've noticed in a locally installed environment everything works fine as long as the client is being used in the main app.vue page. If you remove the client use from app.vue using it within the pages directory starts throwing errors.

Also, I usually use firefox, but using chromium gave a different, perhaps more useful error: `The requested module '/_nuxt/node_modules/.cache/vite/client/deps/vue.js?v=1b68b304' does not provide an export named 'Component'`

Here is my stack:
frontend
- Nuxt 3
- npm
- nuxi as run command
- nuxt-open-fetch@latest

backend
- Django 5.0
- Django rest framework
- drf-spectacular as the generator of the openAPI schema
