### ISSUE TITLE
Use request fetch on SSR

### ISSUE THREAD

**Issue by philschleier** [enkot/nuxt-open-fetch#32]
Hi,

we are proxying our API through a nuxt catch-all server route. The server route authenticates the API call based on the user's session.

On SSR, this works fine with useFetch(), as it falls back to useRequestFetch() for local calls on the server side:

https://github.com/nuxt/nuxt/blob/a80d1a0d6349bf1003666fc79a513c0d7370c931/packages/nuxt/src/app/composables/fetch.ts#L170-L176

Since the $fetch instance in nuxt-open-fetch is always globalThis.$fetch via createOpenFetch, the above behaviour cannot be used and thus `use[Client]` behaves differently from `useFetch` for SSR.

Am I correctly assuming that this can be achieved by basically copying the above snippet to select the $fetch instance into `createOpenFetch` and would you be open to such a PR?

Thanks

**Comment by enkot** [comment]
Hi @philschleier,

Good catch! Yes, PR would be great :)

**Comment by adamdehaven** [comment]
@enkot is this something you can implement? I'm seeing different behavior in SSR as well and it's a blocker in using the package 😬

**Comment by adamdehaven** [comment]
I tried manually providing the `useRequestFetch` to the `$fetch` option; however, it does not properly perform the `path` replacements

**Comment by enkot** [comment]
@philschleier @adamdehaven Should be fixed in https://github.com/enkot/nuxt-open-fetch/releases/tag/v0.9.0 :)
Please, let me know if you have any problem.

**Comment by adamdehaven** [comment]
I'll definitely check it out, thanks!

**Comment by adamdehaven** [comment]
@enkot looking at your updated docs example:

```ts
export default defineNuxtPlugin({
  enforce: 'pre', // clients will be ready to use by other plugins, Pinia stores etc.
  setup() {
    const clients = useRuntimeConfig().public.openFetch
    const localFetch = useRequestFetch()

    return {
      provide: Object.entries(clients).reduce((acc, [name, client]) => ({
        ...acc,
        [name]: createOpenFetch(localOptions => ({
          ...options,
          ...localOptions,
          onRequest(ctx) {
            console.log('My logging', ctx.request)
            return localOptions?.onRequest?.(ctx)
          }
        }), localFetch)
      }), {})
    }
  }
})
```

Should `client` (extracted from the array) actually be `options` as it was previously? Otherwise, I'm not sure where `...options` come from in the new example? (Please double-check me, maybe I'm missing something)

**Comment by adamdehaven** [comment]
I locally switched my configuration to `options` as suggested above and everything seems to be working correctly for me (so I think just the docs example needs to be fixed)

**Comment by adamdehaven** [comment]
@enkot I'm also noticing that my `NuxtApp` interface does not automatically pick up my custom client (or any clients).

I tried manually adding the interface but this cannot be resolved when I actually run the build:

```ts
import type { paths as ApiPaths } from '#open-fetch-schemas/api'
```

**Comment by enkot** [comment]
What Nuxt version do you use?
Looks like it doesn't resolve on Nuxt 3.11.2 for some reason, but works fine on 3.12.2

**Comment by adamdehaven** [comment]
I'm on `3.12.2` and it's not working for me 😬

**Comment by adamdehaven** [comment]
I'm also having to manually declare the `$api` interface because it doesn't seem to be automatically added for me?

```typescript
// nuxt-app.d.ts
import type { paths as ApiPaths } from '#open-fetch-schemas/api'
import type { OpenFetchClient } from '#imports'

declare module '#app' {
  interface NuxtApp {
    $api: OpenFetchClient<ApiPaths>
  }
}
```

**Comment by enkot** [comment]
@adamdehaven Did you try removing the lock file and reinstall deps? Possibly @nuxt/kit has different version to Nuxt.

**Comment by adamdehaven** [comment]
I have tried that, but I can also try manually bumping nuxtkit. 

I'm in a mono repo that also uses layers. 

I opened this issue (as I've seen the problem several times now): https://github.com/nuxt/nuxt/issues/27693

You could try exporting one extra interface like I outline in the ticket, but unsure if that's an actual solution or just a workaround.

**Comment by adamdehaven** [comment]
@enkot using a mono repo + layers setup like referenced above, I can't get past the error shown below:

<img width="709" alt="image" src="https://github.com/enkot/nuxt-open-fetch/assets/2229946/45b5d744-5301-44ad-bf3b-3cf7cee7c351">

When I run the dev server everthing is fine; however, when I run the build, my project is choking on the aliased import paths 😢

**Comment by jonkri** [comment]
Not sure if it's related to this issue (I'm probably doing something silly since I'm new to nuxt-open-fetch) but I'm having problems with SSR using nuxt-open-fetch 0.9.0.

This code server-side renders fine without any hydration errors:

```html
<template>
  {{ data }}
</template>

<script setup lang="ts">
  const data = ref<any>(null);

  // SSR ✅; Ny hydration error ✅
  data.value = (await useFetch("/api/test")).data;
</script>
```

However, this this code server-side renders (in that I can see the generated code when I view the document source) but flickers (there is a very brief moment when the document is empty). It also generates a hydration error (in which the client expects the `data` markup not to be rendered):

```html
<template>
  {{ data }}
</template>

<script setup lang="ts">
  const data = ref<any>(null);

  // SSR ✅; Hydration error ❌
  data.value = (await useApi("/test")).data;
</script>
```

**Comment by jonkri** [comment]
Oh, I should mention I'm also using a catch-all server route.

`server/api/[...].ts`:

```ts
import { defineEventHandler, H3Event, parseCookies, setCookie } from "h3";
import { joinURL } from "ufo";

export default defineEventHandler(async (event: H3Event) => {
  const cookies = parseCookies(event),
    { proxyUrl } = useRuntimeConfig(),
    target = joinURL(proxyUrl, event.path),
    token = cookies?.token;

  setCookie(event, "token", token);

  return proxyRequest(event, target);
});
```

**Comment by jonkri** [comment]
I'm not sure what's going on here but I realized that an empty object options argument to `useApi` got rid of the error:

Without the object (code identical to above):

```ts
// SSR ✅; Hydration error ❌
data.value = (await useApi("/test")).data;
```

With the object:

```ts
// SSR ✅; No hydration error ✅
data.value = (await useApi("/test", {})).data;
```

It does't matter if the object is added or not if I get the client from `useNuxtApp`:

```ts
const { $api } = useNuxtApp();
data.value = await($api as any)("/test"); // SSR ✅; No hydration error ✅
```

```ts
const { $api } = useNuxtApp();
data.value = await($api as any)("/test", {}); // SSR ✅; No hydration error ✅
```

By the way, `$api` is of the type `unknown` for me. I'm using version 3.12.2 of both Nuxt and @nuxt/kit.
