### ISSUE TITLE
Better documentation on how to set parameters like headers/method, etc. for each fetch call

### ISSUE THREAD

**Issue by twatzl** [enkot/nuxt-open-fetch#33]
Currently the documentation is quite minimal on the topic of how to do post request, how to pass header parameters or further advanced topics.

Also there is no documentation on how to make use of the typing when using ides or editors such as VSCode or Intellij.

It would be helpful to add this.

**Comment by enkot** [comment]
Hi @twatzl,

You can use the Nuxt documentation for [useFetch](https://nuxt.com/docs/api/composables/use-fetch) and [$fetch](https://nuxt.com/docs/api/utils/dollarfetch) as mentioned in the [docs](https://nuxt-open-fetch.vercel.app/composables/useclient):

> It has the same API as Nuxt's [useFetch](https://nuxt.com/docs/api/composables/use-fetch) composable with additional `path` option, which is used to replace params in the pathname.
