### ISSUE TITLE
Cannot write post-request with request body

### ISSUE THREAD

**Issue by uykusuz** [enkot/nuxt-open-fetch#37]
Hi,

thank you for your work in this module!

I want to do a post request with a request body. I created a changeset of the problem [here](https://github.com/enkot/nuxt-open-fetch/compare/main...uykusuz:bug-post-requestbody?expand=1).

I add the following line to `playground/app.vue`:

`
await $pets('/store/order', { body: { petId: petId.value }})
`

That won't compile with the following error:
`
Argument of type '{ body: { petId: number; }; }' is not assignable to parameter of type 'OpenFetchOptions<"post" | "POST", "post", { post: { requestBody?: { content: { "application/json": { id?: number | undefined; petId?: number | undefined; quantity?: number | undefined; shipDate?: string | undefined; status?: "placed" | ... 2 more ... | undefined; complete?: boolean | undefined; }; "application/xml":...'.
  Property 'method' is missing in type '{ body: { petId: number; }; }' but required in type '{ method: "post" | "POST"; }'.ts(2345)
fetch.ts(14, 77): 'method' is declared here.
`

When I do what TS wants, i.e. add that `method` parameter with a value of `"post"` it doesn't work either. Now it tells me the following:
`
Argument of type '{ method: "post"; body: { petId: number; }; }' is not assignable to parameter of type 'OpenFetchOptions<"post", "post", { post: { requestBody?: { content: { "application/json": { id?: number | undefined; petId?: number | undefined; quantity?: number | undefined; shipDate?: string | undefined; status?: "placed" | ... 2 more ... | undefined; complete?: boolean | undefined; }; "application/xml": { ...; }...'.
  Type '{ method: "post"; body: { petId: number; }; }' is not assignable to type 'Record<string, never>'.ts(2345)
`

I tried digging into types, tried google, I cannot find the cause of the problem.

Is this a bug in nuxt-open-fetch or am I doing something wrong?

Thank you in advance for your response!

Regards,
Boris

**Comment by enkot** [comment]
Hi @uykusuz,

Good catch, it's definitely a bug!

**Comment by enkot** [comment]
@uykusuz Fixed in [v0.7.0](https://github.com/enkot/nuxt-open-fetch/releases/tag/v0.7.0)

**Comment by uykusuz** [comment]
Wow awesome, thank you!

-------- Original Message --------
