### ISSUE TITLE
Is it possible to dynamically change baseURL of a client ?

### ISSUE THREAD

**Issue by GreyXor** [enkot/nuxt-open-fetch#42]
Hello,
now i'm doing this

```ts
  useApi('/foo', {
    baseURL: serverStore.host,
  })
```
Because sometime I need to use another host. Is it the only way to dynamically change the baseURL or can we also change the default baseURL for all client ?
Thanks

**Comment by enkot** [comment]
@GreyXor If you need to change it
- once during build, you can do it inside nuxt.config or using env variables - https://nuxt-open-fetch.vercel.app/setup/configuration
- once on the app load, you can create custom plugin and change any option there - https://nuxt-open-fetch.vercel.app/advanced/custom-client
- each time you call the `$fetch`/`useFetch` (your example)

**Comment by enkot** [comment]
I activated the [Discussions](https://github.com/enkot/nuxt-open-fetch/discussions), you can ask any question there 💪
