### ISSUE TITLE
Add docs for disableNitroPlugin

### ISSUE THREAD

**Issue by letoast** [enkot/nuxt-open-fetch#43]
https://github.com/enkot/nuxt-open-fetch/blob/main/src/module.ts#L32

It would be also nice to document the `${client} = useNitroApp()` server functionality in general.

And also extending the type of `useNitroApp()`. Currently I'm solving this locally by adding a:
```ts
// open-api-fetch.d.ts
declare module 'nitropack' {
	interface NitroApp {
		$pets: OpenFetchClient<PetsPaths>
	}
}

export {}
```

**Comment by enkot** [comment]
@letoast Updated the docs - https://nuxt-open-fetch.vercel.app/utils/dollarclient.
Types should work out of the box, could you please recheck?

**Comment by enkot** [comment]
I activated the [Discussions](https://github.com/enkot/nuxt-open-fetch/discussions), so you can ask any question there 💪
