### ISSUE TITLE
Accessing the response type for a certain request

### ISSUE THREAD

**Issue by jonkri** [enkot/nuxt-open-fetch#45]
I'm wondering how I can access the response type for a certain request.

I would like to type my Pinia store without having to type something like this:

```ts
export const useStore = defineStore("test", {
  // ...
  state: () => ({
    token: null as null | string,
    userInfo: null as {
      deactivate?: string | undefined;
      email: string;
      id: string;
      instances: {
        id: string;
        name: string;
      }[];
      name: string;
      phone?: string | undefined;
      roles: string[];
    } | null
  })
});
```

Ideally the code would look something like this:

```ts
export const useStore = defineStore("test", {
  // ...
  state: () => ({
    token: null as null | string,
    userInfo: null as UserInfoByToken | null
  })
});
```

Here's the code I'm using to set `userInfo`:

```ts
const { data, error } = await useAuthService(
  "/user-info-by-token/{token}",
  {
    path: { token: this.token }
  }
);

this.userInfo = data.value;
```

@jd-solanki kindly suggested importing the `operations` type like so (see https://github.com/enkot/nuxt-open-fetch/issues/31#issuecomment-2177788952):

```ts
import type { operations } from '#build/types/open-fetch/schemas/api'
```

However, I'm not sure how to use `operations` to access the response type. `operations` is of the type:

```ts
type operations = {
    [x: string]: never;
}
```

Thanks for a great module!

**Comment by jd-solanki** [comment]
Wherever you want to access the type of request or response add below line at the top:
```ts
import type { operations } from '#build/types/open-fetch/schemas/api'
```

Now navigate to `'#build/types/open-fetch/schemas/api'` by clicking with control/cmd key and this `api` file will open where you'll see all the definition of your routes.

Find your route in that definition and use bracket syntax to access the type: `operations[...][...]`

For example, To access type of response for `/chats/:id` route of my backend I'll use below
```ts
type Response = operations['get_chats__id']['responses'][200]['content']['application/json']
```

Here, `get_chats__id` is my OpenAPI route name.

I hope this will help you get the type. Also if you're not sure autocompletion will help you when you write `operations['']` place your custor between quotes and press `ctrl+space`.

**Comment by jonkri** [comment]
@jd-solanki: Thanks again, but I don't get any relevant suggestions when I place the cursor between the quotes and press `ctrl+space`. This is how the `operations` type is defined in the “api” file:

```ts
export type operations = Record<string, never>;
```

I'm tried both version 0.8 and 0.9 of nuxt-open-fetch. I'm using version 3.12.2 of Nuxt and @nuxt/kit.

The OpenAPI 3.0 spec in question can be found here: [auth-service.json](https://github.com/user-attachments/files/15936581/auth-service.json).

**Comment by enkot** [comment]
@jd-solanki Thank you for help! 
@jonkri The OpenAPI file you provided doesn't use`operationId` fields, thats why there are no `operations` generated.
Personally, the schema you provided looks somehow incomplete to me, but valid 🙂

**Comment by enkot** [comment]
@jonkri I activated the [Discussions](https://github.com/enkot/nuxt-open-fetch/discussions), so you can ask any question there.
