### ISSUE TITLE
TypeScript error in Custom client example

### ISSUE THREAD

**Issue by jonkri** [enkot/nuxt-open-fetch#46]
I'm getting a TypeScript error when I use this code from https://nuxt-open-fetch.vercel.app/advanced/custom-client in a new Nuxt project:

```ts
export default defineNuxtPlugin({
  enforce: "pre", // clients will be ready to use by other plugins, Pinia stores etc.
  setup() {
    const clients = useRuntimeConfig().public.openFetch;
    const localFetch = useRequestFetch();

    return {
      provide: Object.entries(clients).reduce(
        (acc, [name, options]) => ({
          ...acc,
          [name]: createOpenFetch(options, localFetch)

          // or add the logging:

          // [name]: createOpenFetch(localOptions => ({
          //   ...options,
          //   ...localOptions,
          //   onRequest(ctx) {
          //     console.log('My logging', ctx.request)
          //     return localOptions?.onRequest?.(ctx)
          //   }
          // }), localFetch)
        }),
        {}
      )
    };
  }
});
```

The error appears on the `localFetch` parameter to the `createOpenFetch` call. The error is:

```
Expected 1 arguments, but got 2
```

**Comment by jonkri** [comment]
Reading through the page linked above I got two questions:

1. Is there a way to set headers on the outgoing request, for example a `Authorization` header?
2. Under what general circumstances would one need to disable the Nitro plugin and provide a custom fetch client?

**Comment by enkot** [comment]
Can't reproduce

> I'm getting a TypeScript error when I use this code from https://nuxt-open-fetch.vercel.app/advanced/custom-client in a new Nuxt project:
> 
> ```ts
> export default defineNuxtPlugin({
>   enforce: "pre", // clients will be ready to use by other plugins, Pinia stores etc.
>   setup() {
>     const clients = useRuntimeConfig().public.openFetch;
>     const localFetch = useRequestFetch();
> 
>     return {
>       provide: Object.entries(clients).reduce(
>         (acc, [name, options]) => ({
>           ...acc,
>           [name]: createOpenFetch(options, localFetch)
> 
>           // or add the logging:
> 
>           // [name]: createOpenFetch(localOptions => ({
>           //   ...options,
>           //   ...localOptions,
>           //   onRequest(ctx) {
>           //     console.log('My logging', ctx.request)
>           //     return localOptions?.onRequest?.(ctx)
>           //   }
>           // }), localFetch)
>         }),
>         {}
>       )
>     };
>   }
> });
> ```
> 
> The error appears on the `localFetch` parameter to the `createOpenFetch` call. The error is:
> 
> ```
> Expected 1 arguments, but got 2
> ```

Can't reproduce, please try to provide reproduction next time using Stackblitz/Codesandbox or Github repo.
I suspect you have old module version installed, try to upgrade.

**Comment by enkot** [comment]
> Under what general circumstances would one need to disable the Nitro plugin and provide a custom fetch client?
> 
> Related to #43.

Please, check the docs here 🙂  - https://nuxt-open-fetch.vercel.app/advanced/custom-client.
Also, I activated the [Discussions](https://github.com/enkot/nuxt-open-fetch/discussions), you can ask any question there 💪
