### ISSUE TITLE
Request and response interceptors

### ISSUE THREAD

**Issue by jonkri** [enkot/nuxt-open-fetch#49]
Can request and response interceptors be implemented without using a [custom client](https://nuxt-open-fetch.vercel.app/advanced/custom-client)? If so, how?

If a custom client is necessary, how can a custom client be implemented in a way such that `useCookie` works in [my catch-all server route](https://github.com/enkot/nuxt-open-fetch/issues/32#issuecomment-2183189424)?

`token` contains...

- `undefined` when a custom client is used, and
- the desired cookie value when a custom client is used.

**Comment by enkot** [comment]
@jonkri Please, check Nuxt docs how interceptors can be used - https://nuxt.com/docs/api/composables/use-fetch#usage, anything you use with `useFetch` can be used with `use[Client]`.
