### ISSUE TITLE
Using “$[client]” in mounted components

### ISSUE THREAD

**Issue by jonkri** [enkot/nuxt-open-fetch#50]
Is using the “$[client]” generated wrapper the intended way to use nuxt-open-fetch when components are mounted?

When I try to use “use[Client]” when a component is mounted I'm getting a warning.

This code doesn't display a warning:

```html
<script setup lang="ts">
  const data = ref<any>(null);
  data.value = (await useApi("/test")).data;
</script>
```

However, this code...

```ts
<script setup lang="ts">
  const data = ref<any>(null);

  async function onClick() {
    data.value = (await useApi("/courses")).data;
  }
</script>
```

... displays this warning in the console when the function is activated:

```text
[nuxt] [useFetch] Component is already mounted, please use $fetch instead. See https://nuxt.com/docs/getting-started/data-fetching
```

Can “$[client]” be used when components are mounted without triggering this warning and if so how?

**Comment by enkot** [comment]
@jonkri NuxtOpenFetch is just a wrapper for Nuxt's `useFetch`. See the Nuxt docs for why useFetch is not recommended inside `mounted` - https://nuxt.com/docs/getting-started/data-fetching.

**Comment by jonkri** [comment]
@enkot: To clarify, I'm not using “use[Client]” in `mounted`, it's at the top-level of the Composition API component.

What I meant to say was that the error seems to occur when the component hydrates. (I can see the page render initially but then I see a 500 Internal Server Error page.)

This code works:

```vue
<template>{{ test.test }}</template>

<script lang="ts" setup>
  const test = (await useFetch("/api/test")).data;
</script>
```

This code server-side renders but then generates a 500 Internal Server Error page with `$setup.test is null`:

```vue
<template>{{ test.test }}</template>

<script lang="ts" setup>
  const test = (await useApi("/test")).data;
</script>
```

Using `$api` works:

```vue
<template>{{ test.test }}</template>

<script lang="ts" setup>
  const { $api } = useNuxtApp();
  const test = await $api("/test");
</script>
```

Why isn't `useApi` working like `useFetch` here?

**Comment by jonkri** [comment]
Created a bug report for the problem: https://github.com/enkot/nuxt-open-fetch/issues/62.
