### ISSUE TITLE
Type interface for client query should allow for reactive values

### ISSUE THREAD

**Issue by adamdehaven** [enkot/nuxt-open-fetch#52]
### Environment

- Operating System: Darwin
- Node Version:     v20.14.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/adamdehaven/nuxt-open-fetch/tree/chore/query-interface-error

Ensure you checkout the `chore/query-interface-error` branch.

If you run the playground with `pnpm dev` you'll notice I also added a `<select>` element at the top to demonstrate the reactivity works correctly; it's just an issue with the `query[property]` type interface(s).

### Describe the bug

Nuxt's `useFetch` (the underlying implementation under `use[client]` allows for passing in reactive `ref` values for the `query` property:

```typescript
// Example source: https://nuxt.com/docs/api/composables/use-fetch#usage

const param1 = ref('value1')
const { data } = await useFetch('/api/modules', {
  query: { 
    param1, // Reactive 
    param2: 'value2', 
  }
})
```

Clients generated by `nuxt-open-fetch` _actually do work_ with this implementation; however, the type interface shows an error as the properties are typed only to the raw value.

## Example

Utilizing the `/playground/app.vue` file from this repo, if I change the existing `/pet/{petId}` call to this:

```typescript
const status = useState<'available' | undefined>(() => undefined)
const { data, execute } = await usePets('/pet/findByStatus', {
  immediate: false,
  query: {
    status, // This query points to a reactive variable
  },
})
```

I see the following TypeScript error:

![typescript error](https://github.com/enkot/nuxt-open-fetch/assets/2229946/31ceeee1-74c6-4181-94ec-9d88fe7d9652)

However, you'll notice if you actually run the playground, not only is the example fully-functional, but it also **correctly** auto-watches the `query.status` property and runs the query again when the `status` ref changes.

If I change `usePets` to the native `useFetch` you'll notice there are no type errors, and the `query.status` property is correctly typed:
![no error](https://github.com/enkot/nuxt-open-fetch/assets/2229946/c0cf86fc-ede7-45fd-a5d0-3a80d29d2edc)

### Additional context

Functionality is correct, but the type interfaces for `query` properties need to allow for both static and reactive values, just like the native `useFetch`.

**Comment by adamdehaven** [comment]
@enkot I'm trying to figure out where the interface needs to be modified; glad to help if you want to take a look

**Comment by adamdehaven** [comment]
@enkot just bumping this and https://github.com/enkot/nuxt-open-fetch/pull/53 again if possible?

Let me know if I can provide more info

**Comment by enkot** [comment]
Hi @adamdehaven 

Thank you for the issue!
Should be fixed in https://github.com/enkot/nuxt-open-fetch/releases/tag/v0.9.4
