### ISSUE TITLE
Add dynamic headers

### ISSUE THREAD

**Issue by schillerenrico** [enkot/nuxt-open-fetch#55]
### Describe the feature

Is there a way to add and remove headers for all request? Instead of adding the auth header each time I do a request I want the default request have my dynamically generated header added or removed while runtime

### Additional information

- [X] Would you be willing to help implement this feature?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/enkot/nuxt-open-fetch/discussions) and [issues](https://github.com/enkot/nuxt-open-fetch/issues).

**Comment by adamdehaven** [comment]
You should be able to do that via a [Custom Client](https://nuxt-open-fetch.vercel.app/advanced/custom-client)

Based on the example from the docs that adds the logging:

```typescript
export default defineNuxtPlugin({
  enforce: 'pre', // clients will be ready to use by other plugins, Pinia stores etc.
  setup() {
    const clients = useRuntimeConfig().public.openFetch
    const localFetch = useRequestFetch()

    return {
      provide: Object.entries(clients).reduce((acc, [name, options]) => ({
        ...acc,
        [name]: createOpenFetch(localOptions => ({
          ...options,
          ...localOptions,
          onRequest(ctx) {
            ctx.options.headers = {
              ...ctx.options.headers || {},
              // Add the Authorization header to all requests
              Authorization: `Bearer ${session.token}`, // Wherever your token comes from
            }
            return localOptions?.onRequest?.(ctx)
          }
        }), localFetch)
      }), {})
    }
  }
})
```

**Comment by schillerenrico** [comment]
Thanks for the fast reply! You are definitly right and it should be the right approch.
I just have some issues by using this code.

First of all there are 2 typescript errors:
![image](https://github.com/user-attachments/assets/aed73bef-bd6e-4ef6-a084-6cc0e92d8e50)
![image](https://github.com/user-attachments/assets/66925e68-29cc-4ca5-b0d9-d81c25e3977d)

and when implementing the code the frontend shows a 500 with the message:
Cannot redefine property: $[InsertOpenFetchClientNameHere]

**Comment by adamdehaven** [comment]
For the "Cannot redefine property" error, you'll also need to disable the nuxt plugin:

```typescript
export default defineNuxtConfig({
  openFetch: {
    disableNuxtPlugin: true,
    // ...
  },
})
```

**Comment by schillerenrico** [comment]
the main problem is solved, thanks a lot @adamdehaven 
only the typescript error remains dont know if we should keep this issue open for it
