### ISSUE TITLE
'__VLS_ctx.assignment' is possibly 'null'

### ISSUE THREAD

**Issue by jonkri** [enkot/nuxt-open-fetch#57]
### Describe the feature

Using the generated clients I'm getting...

> '__VLS_ctx.assignment' is possibly 'null'

... errors everywhere the data is used.

Is there some convenient way around this except adding a non-null assertions everywhere the data is used?

Thanks!

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/enkot/nuxt-open-fetch/discussions) and [issues](https://github.com/enkot/nuxt-open-fetch/issues).

**Comment by enkot** [comment]
Please, add a reproduction.
Closing for now.
