### ISSUE TITLE
Automatic Refresh and Rebuild for Nuxt with Schema Changes

### ISSUE THREAD

**Issue by cannap** [enkot/nuxt-open-fetch#59]
### Describe the feature

Hi, I use Elysia in combination with Nuxt. When I make changes to my API on the server, it would be nice if I could trigger a refresh after a certain number of minutes when my API changes, so that Nuxt can build the new TypeScript files. I'm not sure if this is possible at runtime, though. Thanks for the module!

### Additional information

- [X] Would you be willing to help implement this feature? ( i am thinking) 

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/enkot/nuxt-open-fetch/discussions) and [issues](https://github.com/enkot/nuxt-open-fetch/issues).

**Comment by enkot** [comment]
It is not possible in runtime unfortunately. Although this can be done, it is beyond the scope of this module.

I would use a client from Elysia itself - https://elysiajs.com/eden/overview.html#eden-treaty-recommended.
