### ISSUE TITLE
Dynamic base URL

### ISSUE THREAD

**Issue by jonkri** [enkot/nuxt-open-fetch#60]
### Describe the feature

Using Nuxt 2, I'm configuring the base URL dynamically based on both `process.client` and `process.env.NODE_ENV` like so:

```js
$axios.defaults.baseURL = process.client
  ? process.env.NODE_ENV === 'production'
    ? 'https://...'
    : 'http://...'
  : process.env.NODE_ENV === 'production'
  ? 'http://...'
  : 'https://...'
```

I would like to be able to do this (presumably with `import.meta.server` instead of `process.client`) using NuxtOpenFetch and Nuxt 3.

Thanks for a great library!

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/enkot/nuxt-open-fetch/discussions) and [issues](https://github.com/enkot/nuxt-open-fetch/issues).

**Comment by enkot** [comment]
Hi @jonkri,

You can create a custom plugin.
```ts
export default defineNuxtPlugin({
  enforce: 'pre',
  setup() {
    const clients = useRuntimeConfig().public.openFetch
    const $fetch = useRequestFetch()

    return {
      provide: Object.fromEntries(Object.entries(clients).map(([name, options]) => [
        name,
        createOpenFetch({
          ...options,
          baseURL: name === 'pets' ? getBaseUrlForPets() : options.baseURL
        }, $fetch),
      ]))
    }
  },
})

```
Then disable the built-in plugin in the `./nuxt.config.ts`:
```ts
export default defineNuxtConfig({
  openFetch: {
    disableNuxtPlugin: true
  },
})
```
