### ISSUE TITLE
Getting "Failed to resolve import" after upgrading to 0.9.1 from 0.8.0

### ISSUE THREAD

**Issue by tokula** [enkot/nuxt-open-fetch#63]
### Environment

Nuxt project info:                                                                                                                                                                                                       20.02.21  

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.17.0
- Nuxt Version:     3.13.0
- CLI Version:      3.13.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      compatibilityDate, devtools, modules, openFetch
- Runtime Modules:  nuxt-open-fetch@0.9.1
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/tokula/nuxt-open-fetch-issue

### Describe the bug

After upgrading from 0.8.0 to 0.9.1 I get:
> Pre-transform error: Failed to resolve import "#open-fetch-schemas/pets-api" from "utils/petutils.ts". Does the file exist?

In the minimal reproduction you should get the error after upgrading to 0.9.1.

I'm guessing it could be related to this change https://github.com/enkot/nuxt-open-fetch/pull/47

**Comment by schillerenrico** [comment]
guess this is related https://github.com/enkot/nuxt-open-fetch/issues/71

**Comment by enkot** [comment]
Hi @tokula,

Sorry for long delay.

You can only import types from `#open-fetch-schemas/*`.
