### ISSUE TITLE
useAsyncData wrapper?

### ISSUE THREAD

**Issue by TheDutchCoder** [enkot/nuxt-open-fetch#65]
### Describe the feature

Hey there!

This module seems promising and has some nice features, but the main issue for us is that it lacks a `useAsyncData` wrapper.

`useFetch` isn't as optimal for SSR where `useAsyncData` is more appropriate. So it would be great if the module came with a wrapper for that as well. Maybe something like `useAsync[client]`?

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/enkot/nuxt-open-fetch/discussions) and [issues](https://github.com/enkot/nuxt-open-fetch/issues).

**Comment by c0nd3v** [comment]
Couldn't you just do:

```js
const { $pets } = useNuxtApp()

const url = '/api/test';
const { data } = useAsyncData(url, (url) => $pets(url));
```

**Comment by TheDutchCoder** [comment]
Yes, but I'm taking about a wrapper so you don't have to do this manually. We have 100's of routes and would like something simple like usePetsAsync where the key and fetch are abstracted away.

**Comment by c0nd3v** [comment]
What about:
```javascript
const { data } = await usePets("/api/test", { key: "examplekey" });
```

**Comment by TheDutchCoder** [comment]
useFetch and useAsyncData are not the same thing.

**Comment by c0nd3v** [comment]
As far as I know, useFetch is just a wrapper for useAsyncData + $fetch. Am I missing something?

**Comment by enkot** [comment]
Hi @TheDutchCoder 
The useAsyncData is just a composable to run asynchronous operations and return reactive result. As mentioned by @c0nd3v, it has nothing to do with APIs directly.

**Comment by TheDutchCoder** [comment]
It is, but is primarily built for client-side calls and doesn't have the same SSR advantages as useAsyncData directly.

It also doesn't support things like transformers.

**Comment by enkot** [comment]
@TheDutchCoder please, read Nuxt docs more carefully, useFetch is actually created to handle SSR and supports transformers - https://nuxt.com/docs/api/composables/use-fetch

**Comment by enkot** [comment]
@TheDutchCoder if you have problems with SSR, please share the example. I will be glad to help :)

**Comment by TheDutchCoder** [comment]
After re-reading the docs, it seems indeed useFetch (and the compisables this module generates) might actually be enough for us. My apologies.

I have another issue opened because the module fails typechecking (and use env vars), but they're unrelated to this.
