### ISSUE TITLE
`openAPITS` option doesn't support `output` flag

### ISSUE THREAD

**Issue by TheDutchCoder** [enkot/nuxt-open-fetch#66]
### Describe the feature

https://openapi-ts.pages.dev/node#options supports an output flag which we use to have the types available locally and extract manual types from (mainly parameters and request bodies).

It would be good to support this in the module as well, so the generated file doesn't end up in `.output` during dev time, but actually becomes a file you can commit to your repo.

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/enkot/nuxt-open-fetch/discussions) and [issues](https://github.com/enkot/nuxt-open-fetch/issues).

**Comment by datWeazel** [comment]
+1 would be nice if this was supported.

**Comment by enkot** [comment]
Hi @TheDutchCoder,

Unfortunately it is beyond the scope of this module. `openAPITS` takes all options `openapiTS()` function takes.

Under the hood:
```ts
import openapiTS from 'openapi-typescript'

const ast = await openapiTS(schema, openAPITS)
```

What you can do is add a script to the json package:
```json
  "scripts": {
    "generateSchemaTypes": "npx openapi-typescript schema.yaml -o /my-custom-location/schema.ts"
  }
```
