### ISSUE TITLE
Environment variables don't work

### ISSUE THREAD

**Issue by TheDutchCoder** [enkot/nuxt-open-fetch#67]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.7.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      app, robots, auth, components, css, devServer, devtools, eslint, modules, openFetch, router, runtimeConfig, sourcemap, srcDir, experimental, vite, compatibilityDate
- Runtime Modules:  @nuxt/eslint@0.5.1, @nuxtjs/i18n@8.5.0, nuxt-jsonld@2.0.8, @nuxtjs/device@3.1.1, @nuxtjs/robots@4.0.2, @vueuse/nuxt@10.11.0, @sidebase/nuxt-auth@0.8.1, nuxt-open-fetch@0.9.2
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-pljepz?file=nuxt.config.ts

### Describe the bug

Env variables are never read on dev start

### Additional context

No matter how/where I declare the variables, or the openfetch options (in the root, or in public config), the env vars are never used.

**Comment by TheDutchCoder** [comment]
@enkot Any change you could look into the open issues?

Currently the module seems very useful, but it can't be used in production because the config part doesn't properly work (yet). Would be more than happy to assist btw.

**Comment by TheDutchCoder** [comment]
After digging more, the issue is that the documentation around config is wrong.
The only way to sort of make this work is by defining `openFetch` at the root of the config, _not_ in runtimeConfig and hardcode the baseULR as: `process.env.NUXT_OPEN_FETCH_RENTALS_BASE_URL || 'http://localhost/fallback-url'`

**Comment by enkot** [comment]
Hi @TheDutchCoder,

Added not to the docs - https://github.com/enkot/nuxt-open-fetch/commit/4d8d7dedc782e976325871f7aade85b1bb2d21a6
