### ISSUE TITLE
Allow credentials on the schema endpoint

### ISSUE THREAD

**Issue by TheDutchCoder** [enkot/nuxt-open-fetch#73]
### Describe the feature

Our swagger endpoints are basic-auth protected, so we would like to see an option to pass credentials along when fetching the swagger file to generate the types.

### Additional information

- [X] Would you be willing to help implement this feature?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/enkot/nuxt-open-fetch/discussions) and [issues](https://github.com/enkot/nuxt-open-fetch/issues).

**Comment by schillerenrico** [comment]
Maybe this will be helpful
https://github.com/enkot/nuxt-open-fetch/issues/55

**Comment by emavitta** [comment]
i know this is closed, but i had the same issue and i resolved using the way `openapiTS` manage this.
You can pass a `redocly` [config](https://openapi-ts.dev/node#usage) to the options, managing to [pass an auth header ](https://openapi-ts.dev/cli#auth) to the request when fetching the swagger file.
In my case it worked like this

```js
import process from 'node:process'
import { createConfig } from '@redocly/openapi-core'

const redocly = await createConfig({
  resolve: {
    http: {
      headers: [
        {
          matches: <SCHEMA-URL>,
          name: 'Authorization',
          value: <AUTH>,
        },
      ],
    },
  },
})

export default defineNuxtConfig({
  modules: ['nuxt-open-fetch'],
  openFetch: {
    openAPITS: {
      redocly,
    },
    clients: {
      identity: {
        baseURL: <YOUR-BASE-URL>,
        schema: <SCHEMA-URL>,
      },
    },
  },
})

```
