### ISSUE TITLE
Add option for basic auth on swagger endpoints

### ISSUE THREAD

**Issue by TheDutchCoder** [enkot/nuxt-open-fetch#74]
### Describe the feature

We're going to put basic auth on our swagger endpoints, so it would be great if there was an option to pass credentials along to the endpoint from the config.

### Additional information

- [X] Would you be willing to help implement this feature?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/enkot/nuxt-open-fetch/discussions) and [issues](https://github.com/enkot/nuxt-open-fetch/issues).

**Comment by schillerenrico** [comment]
Maybe this will be helpful
https://github.com/enkot/nuxt-open-fetch/issues/55
